add_newline = false

format = '\[$time$username$directory$git_status$character\] '

[username]
show_always = false
style_user = "white"
format = "[$user]($style) "

[time]
disabled = false
use_12hr = true
style = "white"
format = "[$time]($style) "
time_format = "%-l:%M%P"

[directory]
style = "#d36eff"
truncate_to_repo = false
truncation_length = -1

[character]
format = "$symbol"
success_symbol = "[I](bold green)"
error_symbol = "[I](bold red)"
vimcmd_symbol = "[N](bold green)"

[package]
disabled = true
